server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/urfa_grill
    username: urfa
    password: urfa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

security:
  jwt:
    issuer: urfa-grill
    access-token-expiration-minutes: 15
    refresh-token-expiration-days: 14
    secret: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
